CREATE TABLE [dbo].[user] (
	userId INT IDENTITY(1,1) NOT NULL,
	name NVARCHAR(50) NOT NULL,
	phone NVARCHAR(20) NULL,
	email NVARCHAR(20) NULL,
	avatar NVARCHAR(200) NULL
CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
   userId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY])